"""Version 3 adaptive signal-validity framework."""

from .adapters import (
    CcxtOHLCVAdapter,
    FileMarketDataAdapter,
    MarketDataAdapter,
    OptionalFieldFileAdapter,
    build_adapter,
    merge_optional_fields,
)
from .data_contract import (
    CanonicalDataError,
    CanonicalMarketFrame,
    OPTIONAL_COLUMNS,
    REQUIRED_COLUMNS,
    SCHEMA_VERSION,
    SourceManifest,
    ValidationIssue,
    ValidationReport,
    canonicalize_market_frame,
    stable_frame_hash,
)
from .spectral import (
    CausalFeatureConfig,
    PanelSpec,
    SPECTRAL_SCHEMA_VERSION,
    SpectralFeatureError,
    SpectralFeatureFrame,
    SpectralRunManifest,
    build_causal_series_features,
    build_close_panel,
    build_return_panel,
    compare_registered_panels,
    compute_spectral_feature_frame,
    estimate_correlation,
    spectral_metrics_from_correlation,
    summarize_window_sensitivity,
)
from .spectral_runner import run_spectral_features

__all__ = [
    "CanonicalDataError",
    "CanonicalMarketFrame",
    "CausalFeatureConfig",
    "CcxtOHLCVAdapter",
    "FileMarketDataAdapter",
    "MarketDataAdapter",
    "OPTIONAL_COLUMNS",
    "OptionalFieldFileAdapter",
    "PanelSpec",
    "REQUIRED_COLUMNS",
    "SCHEMA_VERSION",
    "SPECTRAL_SCHEMA_VERSION",
    "SourceManifest",
    "SpectralFeatureError",
    "SpectralFeatureFrame",
    "SpectralRunManifest",
    "ValidationIssue",
    "ValidationReport",
    "build_adapter",
    "build_causal_series_features",
    "build_close_panel",
    "build_return_panel",
    "canonicalize_market_frame",
    "compare_registered_panels",
    "compute_spectral_feature_frame",
    "estimate_correlation",
    "merge_optional_fields",
    "run_spectral_features",
    "spectral_metrics_from_correlation",
    "stable_frame_hash",
    "summarize_window_sensitivity",
]
